version: "3.7" 

services:
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: macrowebdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - macroweb-data:/var/lib/mysql
    networks:
      - backend

  macroweb:
    image: macroweb:1.1
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mysqldb
    networks:
      - backend

volumes:
  macroweb-data:
    driver: local

networks:
  backend:   